### ISSUE TITLE
数据加载问题

### ISSUE THREAD

**Issue by xiaboAAA** [coca-huang/ReCoNet#1]
尊敬的作者你好，
        我在复现你的代码的时候，发现训练阶段中数据加载时，出现Dataloader读取数据长度为0的情况，我调整了数据集的位置(TNO)，对应好了meta中txt文件，并且shuffle设置了False，还是报错误：/home/lyu/anaconda3/envs/reconet/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:103: UserWarning: Total length of `CombinedLoader` across ranks is zero. Please make sure this was your intention.  rank_zero_warn(`Trainer.fit` stopped: No training batches.请问作者该如何解决呢？非常感谢您的回答。

**Comment by coca-huang** [comment]
您好，非常感谢您的关注。但由于其他研究人员并未发生此类问题，我认为这可能是在配置时某些路径设置错误。

我有以下几个建议供参考：

1. 请再次确认数据集的路径是否准确，并确保指定的路径下有预期的数据内容。
2. 可以在Dataloader中加入一个小的debug步骤，例如打印出从数据集中读取的一个样本，来确保数据集是被正确读取的。
3. 检查您的meta文件是否与实际的数据集完全匹配，没有遗漏或错误的条目。
4. 如果代码中有分割数据集的部分，请确保训练集的部分确实包含了数据。
5. 最后，也许可以尝试升级或降级PyTorch Lightning的版本，以排除版本不兼容或库中的错误。

希望以上的建议能帮到您。
预祝实验顺利！
